server.port=8080
spring.application.name=api-gateway

spring.cloud.gateway.mvc.routes[0].id=auth
spring.cloud.gateway.mvc.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=risk
spring.cloud.gateway.mvc.routes[1].uri=http://risk-service:8080
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/risk/**

# Fallback local dev
spring.cloud.gateway.mvc.routes[2].id=auth-local
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/auth/**
